### ISSUE TITLE
Teams balance 

### ISSUE THREAD

**Issue by alemag88** [xAranaktu/F1-Manager-2022-Cheat-Table#2]
Hi,thanks a lot for this script it's amazing.
One question though,
I have edited my team balance and it's working fine but is there any chance to know and modify orger teams balance too?
At the moment I can't see which team is which as on the balance tab there is a number for each team and then the balance next to it.
Thanks

**Comment by xAranaktu** [comment]
In "Teams" table you have names for the teamIDs

![](https://i.imgur.com/m1SGMy2.png)

**Comment by alemag88** [comment]
That's great,thanks a lot
