### ISSUE TITLE
Modding an exe

### ISSUE THREAD

**Issue by Ablomis** [xAranaktu/F1-Manager-2022-Cheat-Table#5]
Is it possible to mod an exe to load changed values automatically?
I'm good at coding but not good at exe modding.
Or is it not possible?

**Comment by xAranaktu** [comment]
I don't know, maybe? But why? It's not how you do that kind of thing. It's easier to write a program which will work externally modifying game memory or an dll which will work internally. Not gonna mention that game executable is 500MB+, while your exe/dll will be <1MB, so it's much easier to share it with others.

**Comment by Ablomis** [comment]
What would be the best course of action, inject a DLL?

**Comment by xAranaktu** [comment]
Some perhaps may argue, but yes, I think dll approach is slightly better. The only problem may be the language and the fact that you would also need an injector for it, but in exchange the only limitation what you can do and what not is your skill, time and imagination.
