### ISSUE TITLE
Game crashed when trying to save the game with ImportDB_On_Save activated

### ISSUE THREAD

**Issue by leo-qih** [xAranaktu/F1-Manager-2022-Cheat-Table#6]
The game crashed when trying to save the game with ImportDB_On_Save activated and the below error message was given.
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000000000105bca0
Game version 1.6.0.92082

**Comment by xAranaktu** [comment]
Yea, that may happen, however the game crashed after the save file has been saved, so when you restart the game and load your save file you should be able to see the changes you made.

**Comment by leo-qih** [comment]
I tried again, did not work for me, the game crashed before the save file got saved.
I tried many different combinations: save the game manually vs trigger the autosave, modify some data before saving vs no modification at all, but neither worked for me.

**Comment by xAranaktu** [comment]
You can try my new python script then :)

[F1-Manager-2022-SaveFile-Repacker](https://github.com/xAranaktu/F1-Manager-2022-SaveFile-Repacker)

**Comment by leo-qih** [comment]
That one worked!
Thanks a lot!
